<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>CA2007</NoWarn>
      <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.Process" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaveState.Core\SaveState.Core.csproj" />
    <ProjectReference Include="..\SaveState.Infrastructure\SaveState.Infrastructure.csproj" />
  </ItemGroup>

</Project>

