using System;
using System.Collections.Generic;

namespace SaveState.Core.Services.Ai.Governance.Models
{
    /// <summary>
    /// Defines how the AI is allowed to write to the canonical world state.
    /// </summary>
    public enum CanonWritePolicy
    {
        /// <summary>
        /// Cannot write to canon at all.
        /// </summary>
        None,

        /// <summary>
        /// Can only suggest changes (e.g., generate a proposal object).
        /// </summary>
        SuggestOnly,

        /// <summary>
        /// Can write to canon but requires explicit user/system confirmation.
        /// </summary>
        ConfirmRequired,

        /// <summary>
        /// Can write directly to canon state (use with extreme caution).
        /// </summary>
        Direct
    }

    /// <summary>
    /// Defines how content generated by this contract should be persisted.
    /// </summary>
    public enum ContentPersistencePolicy
    {
        /// <summary>
        /// Content is ephemeral and should not be stored.
        /// </summary>
        NoPersist,

        /// <summary>
        /// Content can be stored in episodic memory (vector store).
        /// </summary>
        EpisodicOnly,

        /// <summary>
        /// Content can be promoted to canon (subject to CanonWritePolicy).
        /// </summary>
        CanonAllowed
    }

    /// <summary>
    /// Represents a binding contract for an AI Agent or Request.
    /// Defines exactly what is allowed, required, and limited for a specific operation.
    /// </summary>
    public class AiContract
    {
        public string ContractId { get; set; } = Guid.NewGuid().ToString();
        public string Version { get; set; } = "1.0";
        public string Name { get; set; } = "Base Contract";

        /// <summary>
        /// Set of capabilities explicitly allowed by this contract.
        /// </summary>
        public HashSet<AiCapability> AllowedCapabilities { get; set; } = new();

        /// <summary>
        /// Set of tool names that are allowed to be called.
        /// </summary>
        public HashSet<string> AllowedTools { get; set; } = new();

        /// <summary>
        /// Policy for writing to the canonical world state.
        /// </summary>
        public CanonWritePolicy CanonPolicy { get; set; } = CanonWritePolicy.None;

        /// <summary>
        /// List of validators that MUST pass for the output to be accepted.
        /// </summary>
        public HashSet<string> RequiredValidators { get; set; } = new();

        // --- Limits ---

        /// <summary>
        /// Maximum allowed cost for this request (in USD).
        /// </summary>
        public double MaxCostPerRequest { get; set; } = 0.01;

        /// <summary>
        /// Maximum allowed latency in milliseconds.
        /// </summary>
        public int MaxLatencyMs { get; set; } = 5000;

        /// <summary>
        /// Strategy to use if the request fails or violates contract.
        /// </summary>
        public string FallbackStrategy { get; set; } = "DefaultFallback";

        /// <summary>
        /// Persistence policy for generated content.
        /// </summary>
        public ContentPersistencePolicy PersistencePolicy { get; set; } = ContentPersistencePolicy.NoPersist;

        /// <summary>
        /// Creates a restrictive default contract.
        /// </summary>
        public static AiContract Default()
        {
            return new AiContract
            {
                Name = "Default Restrictive",
                AllowedCapabilities = new HashSet<AiCapability> { AiCapability.BasicChat },
                CanonPolicy = CanonWritePolicy.None,
                PersistencePolicy = ContentPersistencePolicy.NoPersist
            };
        }

        /// <summary>
        /// Creates a contract for pure read-only queries.
        /// </summary>
        public static AiContract ReadOnlyQuery()
        {
            return new AiContract
            {
                Name = "Read Only Query",
                AllowedCapabilities = new HashSet<AiCapability> 
                { 
                    AiCapability.BasicChat, 
                    AiCapability.GameAnalysis,
                    AiCapability.Recommendations 
                },
                AllowedTools = new HashSet<string> { "search_knowledge", "query_state" },
                CanonPolicy = CanonWritePolicy.None,
                PersistencePolicy = ContentPersistencePolicy.NoPersist // Queries usually don't need saving
            };
        }

        /// <summary>
        /// Creates a contract for creative writing/roleplay (Episodic memory only).
        /// </summary>
        public static AiContract CreativeRoleplay()
        {
            return new AiContract
            {
                Name = "Creative Roleplay",
                AllowedCapabilities = new HashSet<AiCapability> 
                { 
                    AiCapability.BasicChat,
                    AiCapability.NarrativeGeneration,
                    AiCapability.NpcDialogue,
                    AiCapability.NpcEmotions
                },
                AllowedTools = new HashSet<string> { "*", "!system_core" }, // Allow most tools except system core
                CanonPolicy = CanonWritePolicy.SuggestOnly,
                PersistencePolicy = ContentPersistencePolicy.EpisodicOnly,
                RequiredValidators = new HashSet<string> { "SafetyParam", "ToneCheck" }
            };
        }
    }
}
