using System;
using System.Text;
using Microsoft.Extensions.Logging;
using SaveState.Core.Common;
using SaveState.Core.Mugen.ValueObjects;
using SaveState.Core.Mugen.Services;
using MoveProperties = SaveState.Core.Mugen.ValueObjects.MoveProperties;

namespace SaveState.Infrastructure.Mugen;

/// <summary>
/// Service for exporting MUGEN moves to CNS and CMD file formats.
/// Generates valid MUGEN code from move definitions.
/// </summary>
public class MugenExportService : IMugenExportService
{
    private readonly ILogger<MugenExportService> _logger;

    public MugenExportService(ILogger<MugenExportService> logger)
    {
        _logger = logger;
    }

    public async Task<Result<MoveExportResult>> ExportMoveAsync(
        MugenMoveDefinition move,
        ExportOptions options,
        CancellationToken ct = default)
    {
        try
        {
            _logger.LogInformation("Exporting move '{MoveName}' to {OutputDir}", move.Name, options.OutputDirectory);

            // Ensure output directory exists
            Directory.CreateDirectory(options.OutputDirectory);

            // Generate CNS content
            var cnsContent = GenerateCnsContent(move, options);

            // Generate CMD content
            var cmdContent = GenerateCmdContent(move, options);

            // Generate air version if requested
            string? airCnsContent = null;
            if (options.GenerateAirVersion)
            {
                airCnsContent = GenerateAirVersion(move, options);
            }

            // Write files
            var cnsFilePath = Path.Combine(options.OutputDirectory, $"{move.Name}.cns");
            var cmdFilePath = Path.Combine(options.OutputDirectory, $"{move.Name}.cmd");
            var airFilePath = options.GenerateAirVersion ? Path.Combine(options.OutputDirectory, $"{move.Name}_air.cns") : null;

            await File.WriteAllTextAsync(cnsFilePath, cnsContent, ct);
            await File.WriteAllTextAsync(cmdFilePath, cmdContent, ct);

            if (airCnsContent != null && airFilePath != null)
            {
                await File.WriteAllTextAsync(airFilePath, airCnsContent, ct);
            }

            // Calculate file sizes
            var cnsFileSize = new FileInfo(cnsFilePath).Length;
            var cmdFileSize = new FileInfo(cmdFilePath).Length;
            var airFileSize = airFilePath != null ? new FileInfo(airFilePath).Length : 0;

            var result = new MoveExportResult(
                CnsFilePath: cnsFilePath,
                CmdFilePath: cmdFilePath,
                AirFilePath: airFilePath,
                CnsFileSize: cnsFileSize,
                CmdFileSize: cmdFileSize,
                AirFileSize: airFileSize,
                GeneratedStates: move.States.Select(s => s.StateNumber.ToString()).ToList(),
                Warnings: new[] { "Export completed successfully" });

            _logger.LogInformation("Successfully exported move '{MoveName}': CNS={CnsSize} bytes, CMD={CmdSize} bytes",
                move.Name, cnsFileSize, cmdFileSize);

            return Result.Success(result);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error exporting move '{MoveName}'", move.Name);
            return Result.Failure<MoveExportResult>($"Failed to export move: {ex.Message}");
        }
    }

    private string GenerateCnsContent(MugenMoveDefinition move, ExportOptions options)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(";==============================================================================");
        sb.AppendLine($"; Move: {move.DisplayName}");
        sb.AppendLine($"; Generated by SaveState Move Creator v{move.Metadata.Version}");
        sb.AppendLine($"; Author: {move.Metadata.Author}");
        sb.AppendLine($"; Created: {move.Metadata.Created:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"; Description: {move.Metadata.Description}");
        sb.AppendLine(";==============================================================================");
        sb.AppendLine();

        // State definitions
        foreach (var state in move.States.OrderBy(s => s.StateNumber))
        {
            GenerateStateDefinition(sb, state, move, options);
            sb.AppendLine();
        }

        // Helper states (if any)
        GenerateHelperStates(sb, move, options);

        return sb.ToString();
    }

    private void GenerateStateDefinition(StringBuilder sb, MoveState state, MugenMoveDefinition move, ExportOptions options)
    {
        sb.AppendLine($"[State {state.StateNumber}]");
        sb.AppendLine($"type = {GetStateType(state, move)}");

        if (options.IncludeComments)
        {
            sb.AppendLine($"; {move.DisplayName} - State {state.StateNumber}");
            sb.AppendLine($"; Duration: {state.Duration} frames");
        }

        sb.AppendLine($"movetype = {GetMoveType(move.MoveType)}");
        sb.AppendLine($"physics = {GetPhysicsType(state, move)}");
        sb.AppendLine($"anim = {state.AnimationElement}");

        // Control
        var hasHitboxes = state.Hitboxes.Any();
        sb.AppendLine($"ctrl = {!hasHitboxes}");

        // Velocity
        if (state.Properties.Velocity.X != 0 || state.Properties.Velocity.Y != 0)
        {
            sb.AppendLine($"velset = {state.Properties.Velocity.X}, {state.Properties.Velocity.Y}");
        }

        // Acceleration
        if (state.Properties.Acceleration.X != 0 || state.Properties.Acceleration.Y != 0)
        {
            sb.AppendLine($"accel = {state.Properties.Acceleration.X}, {state.Properties.Acceleration.Y}");
        }

        // Spr priority
        sb.AppendLine("sprpriority = 2");

        // Invincibility
        if (state.Properties.Invincible)
        {
            sb.AppendLine("hitby = SCA, NA, SA, HA, NP, SP, HP, NT, ST, HT");
        }

        // Hitboxes
        foreach (var hitbox in state.Hitboxes)
        {
            GenerateHitbox(sb, hitbox, options);
        }

        // Hurtboxes (if different from default)
        if (state.Hurtboxes.Any())
        {
            sb.AppendLine("; Hurtboxes");
            foreach (var hurtbox in state.Hurtboxes)
            {
                sb.AppendLine($"assertspecial = noautoturn ; Hurtbox: {hurtbox.Type}");
                sb.AppendLine($"clsn2 = {hurtbox.Bounds.X}, {hurtbox.Bounds.Y}, {hurtbox.Bounds.X + hurtbox.Bounds.Width}, {hurtbox.Bounds.Y + hurtbox.Bounds.Height}");
            }
        }

        // Projectiles
        foreach (var projectile in state.Projectiles)
        {
            GenerateProjectile(sb, projectile, options);
        }

        // Effects
        foreach (var effect in state.Effects)
        {
            GenerateEffect(sb, effect, options);
        }

        // State transitions
        GenerateStateTransitions(sb, state, move);

        // Custom properties
        foreach (var prop in state.Properties.CustomProperties)
        {
            sb.AppendLine($"{prop.Key} = {prop.Value}");
        }

        sb.AppendLine();
    }

    private void GenerateHitbox(StringBuilder sb, Hitbox hitbox, ExportOptions options)
    {
        var hitboxType = hitbox.Type.ToString().ToLower();
        var flags = string.Join("", hitbox.HitFlags);

        sb.AppendLine($"clsn1 = {hitbox.Bounds.X}, {hitbox.Bounds.Y}, {hitbox.Bounds.X + hitbox.Bounds.Width}, {hitbox.Bounds.Y + hitbox.Bounds.Height}");

        var hitdef = new StringBuilder();
        hitdef.Append($"hitdef(");
        hitdef.Append($"attr = {GetHitAttribute(hitbox)}, {flags}; ");
        hitdef.Append($"damage = {hitbox.Damage}, {hitbox.GuardDamage}; ");
        hitdef.Append($"hitpause = {hitbox.HitPause}, {hitbox.GuardPause}; ");
        hitdef.Append($"p1pause = {hitbox.PlayerHitPause}, {hitbox.PlayerGuardPause}; ");
        hitdef.Append($"ground.hittime = {hitbox.HitLevel switch { HitLevel.Light => 12, HitLevel.Medium => 15, HitLevel.Heavy => 18, _ => 15 }}; ");
        hitdef.Append($"guard.hittime = {hitbox.HitLevel switch { HitLevel.Light => 8, HitLevel.Medium => 10, HitLevel.Heavy => 12, _ => 10 }}; ");
        hitdef.Append($"ground.velocity = {GetHitVelocity(hitbox)}; ");
        hitdef.Append($"guard.velocity = {GetGuardVelocity(hitbox)}; ");
        hitdef.Append($"air.velocity = {GetAirVelocity(hitbox)}; ");
        hitdef.Append($"fall = {(hitbox.HitLevel >= HitLevel.Medium ? 1 : 0)}");

        sb.AppendLine(hitdef.ToString() + ")");

        if (options.IncludeComments)
        {
            sb.AppendLine($"; Hitbox: {hitbox.Bounds.Width}x{hitbox.Bounds.Height} at ({hitbox.Bounds.X},{hitbox.Bounds.Y})");
        }
    }

    private void GenerateProjectile(StringBuilder sb, Projectile projectile, ExportOptions options)
    {
        sb.AppendLine($"; Projectile {projectile.Id}");
        sb.AppendLine($"helper = {projectile.Id}");
        sb.AppendLine($"helpertype = projectile");
        sb.AppendLine($"name = \"{projectile.Animation}\"");
        sb.AppendLine($"postype = p1");
        sb.AppendLine($"pos = {projectile.Position.X}, {projectile.Position.Y}");
        sb.AppendLine($"vel = {projectile.Velocity.X}, {projectile.Velocity.Y}");
        sb.AppendLine($"accel = {projectile.Acceleration.X}, {projectile.Acceleration.Y}");
        sb.AppendLine($"anim = {projectile.Animation}");
        sb.AppendLine($"removetime = {projectile.Time}");
        sb.AppendLine($"pausemovetime = 0");
        sb.AppendLine($"supermovetime = 0");

        // Hit definition for projectile
        sb.AppendLine($"hitdef(");
        sb.AppendLine($"  attr = S, SP");
        sb.AppendLine($"  damage = {projectile.Damage}, 0");
        sb.AppendLine($"  hitpause = 8, 8");
        sb.AppendLine($"  p1pause = 8, 8");
        sb.AppendLine($"  ground.hittime = 15");
        sb.AppendLine($"  guard.hittime = 10");
        sb.AppendLine($"  ground.velocity = 2, -4");
        sb.AppendLine($"  guard.velocity = -2");
        sb.AppendLine($"  air.velocity = 2, -4");
        sb.AppendLine($"  hitsound = 5, 0");
        sb.AppendLine($"  guardsound = 6, 0");
        sb.AppendLine($"  ground.hittime = 15");
        sb.AppendLine($"  guard.hittime = 10");
        sb.AppendLine($"  p2stateno = 5000");
        sb.AppendLine($"  p2getp1state = 0");
        sb.AppendLine($"  hitflag = {string.Join("", projectile.HitFlags)}");
        sb.AppendLine($"  guardflag = {string.Join("", projectile.HitFlags)}");
        sb.AppendLine($"  hitdamage = {projectile.Damage}");
        sb.AppendLine($"  hits = {projectile.Hits}");
        sb.AppendLine($"  removeonhit = {projectile.RemoveOnHit.ToString().ToLower()}");
        sb.AppendLine($"  removeonblock = {projectile.RemoveOnBlock.ToString().ToLower()}");
        sb.AppendLine($")");

        if (options.IncludeComments)
        {
            sb.AppendLine($"; Projectile: {projectile.Damage} damage, {projectile.Hits} hits, {projectile.Time} frames");
        }
    }

    private void GenerateEffect(StringBuilder sb, ParticleEffect effect, ExportOptions options)
    {
        sb.AppendLine($"; Effect: {effect.Type}");
        sb.AppendLine($"explod(0)");
        sb.AppendLine($"anim = {effect.Animation}");
        sb.AppendLine($"pos = {effect.Position.X}, {effect.Position.Y}");
        sb.AppendLine($"postype = p1");
        sb.AppendLine($"facing = 1");
        sb.AppendLine($"vfacing = 1");
        sb.AppendLine($"bindtime = -1");
        sb.AppendLine($"vel = 0, 0");
        sb.AppendLine($"accel = 0, 0");
        sb.AppendLine($"random = 0, 0");
        sb.AppendLine($"removetime = {effect.Duration}");
        sb.AppendLine($"sprpriority = 3");

        // Custom parameters
        foreach (var param in effect.Parameters)
        {
            sb.AppendLine($"; {param.Key} = {param.Value}");
        }
    }

    private void GenerateStateTransitions(StringBuilder sb, MoveState state, MugenMoveDefinition move)
    {
        // Determine next state
        var stateIndex = Array.IndexOf(move.States.OrderBy(s => s.StateNumber).ToArray(), state);
        var nextState = stateIndex < move.States.Count - 1
            ? move.States.OrderBy(s => s.StateNumber).ElementAt(stateIndex + 1).StateNumber
            : 0; // Return to idle

        if (nextState != 0)
        {
            sb.AppendLine($"[State {state.StateNumber + 1}] ; Auto-transition to next state");
            sb.AppendLine($"type = changestate");
            sb.AppendLine($"trigger1 = time >= {state.Duration}");
            sb.AppendLine($"value = {nextState}");
        }
    }

    private void GenerateHelperStates(StringBuilder sb, MugenMoveDefinition move, ExportOptions options)
    {
        // Generate any additional helper states needed
        if (move.Properties.MeterCost > 0)
        {
            sb.AppendLine(";==============================================================================");
            sb.AppendLine("; Meter Management");
            sb.AppendLine(";==============================================================================");
            sb.AppendLine();
        }
    }

    private string GenerateCmdContent(MugenMoveDefinition move, ExportOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine(";==============================================================================");
        sb.AppendLine($"; Command file for {move.DisplayName}");
        sb.AppendLine($"; Generated by SaveState Move Creator v{move.Metadata.Version}");
        sb.AppendLine(";==============================================================================");
        sb.AppendLine();

        sb.AppendLine("[Remap]");
        sb.AppendLine("x = x");
        sb.AppendLine("y = y");
        sb.AppendLine("z = z");
        sb.AppendLine("a = a");
        sb.AppendLine("b = b");
        sb.AppendLine("c = c");
        sb.AppendLine("s = s");
        sb.AppendLine();

        sb.AppendLine("[Defaults]");
        sb.AppendLine("command.time = 15");
        sb.AppendLine("command.buffer.time = 1");
        sb.AppendLine();

        // Command definition
        sb.AppendLine($"[Command]");
        sb.AppendLine($"name = \"{move.Command}\"");
        sb.AppendLine($"command = {NormalizeCommand(move.Command)}");
        sb.AppendLine($"time = {GetCommandTime(move.Command)}");
        sb.AppendLine();

        // State trigger
        sb.AppendLine("[State -1, Move Trigger]");
        sb.AppendLine("type = changestate");
        sb.AppendLine($"triggerall = command = \"{move.Command}\"");
        sb.AppendLine("triggerall = statetype != A");
        sb.AppendLine("trigger1 = ctrl");
        sb.AppendLine($"value = {move.States.Min(s => s.StateNumber)}");

        if (options.IncludeComments)
        {
            sb.AppendLine($"; {move.DisplayName} - triggered by {move.Command}");
            sb.AppendLine($"; Startup: {move.Properties.StartupFrames}, Active: {move.Properties.ActiveFrames}, Recovery: {move.Properties.RecoveryFrames}");
        }

        // Add meter check if move costs meter
        if (move.Properties.MeterCost > 0)
        {
            sb.AppendLine($"triggerall = power >= {move.Properties.MeterCost}");
        }

        sb.AppendLine();

        return sb.ToString();
    }

    private string GenerateAirVersion(MugenMoveDefinition move, ExportOptions options)
    {
        // Create air version by modifying properties
        var airMove = move.With(
            name: $"{move.Name}_air",
            displayName: $"{move.DisplayName} (Air)",
            properties: new MoveProperties(
                Damage: (int)(move.Properties.Damage * 0.8), // Slightly less damage
                MeterGain: move.Properties.MeterGain,
                MeterCost: move.Properties.MeterCost,
                StartupFrames: Math.Max(1, move.Properties.StartupFrames - 2), // Slightly faster startup
                ActiveFrames: move.Properties.ActiveFrames,
                RecoveryFrames: move.Properties.RecoveryFrames + 5, // More recovery
                FrameAdvantageOnHit: move.Properties.FrameAdvantageOnHit - 2,
                FrameAdvantageOnBlock: move.Properties.FrameAdvantageOnBlock - 2,
                HitStun: move.Properties.HitStun,
                BlockStun: move.Properties.BlockStun,
                HitStop: move.Properties.HitStop,
                BlockStop: move.Properties.BlockStop,
                CausesKnockdown: move.Properties.CausesKnockdown,
                GuardCrush: move.Properties.GuardCrush,
                CounterHit: move.Properties.CounterHit,
                Unblockable: move.Properties.Unblockable,
                ArmorBreak: move.Properties.ArmorBreak,
                KnockdownType: move.Properties.KnockdownType,
                HitEffect: move.Properties.HitEffect,
                GuardEffect: move.Properties.GuardEffect,
                Priority: move.Properties.Priority,
                GroundAirType: GroundAirType.Air,
                Attribute: move.Properties.Attribute,
                Flags: move.Properties.Flags));

        return GenerateCnsContent(airMove, options);
    }

    private string GetStateType(MoveState state, MugenMoveDefinition move)
    {
        if (state.HasHitboxes)
            return "S"; // Standing
        if (move.MoveType == MoveType.Throw)
            return "U"; // Unchanged (for throws)
        return "S";
    }

    private string GetMoveType(MoveType moveType)
    {
        return moveType switch
        {
            MoveType.Normal => "A",
            MoveType.Special => "A",
            MoveType.Super => "A",
            MoveType.Hyper => "A",
            MoveType.Throw => "A",
            _ => "I"
        };
    }

    private string GetPhysicsType(MoveState state, MugenMoveDefinition move)
    {
        return move.Category switch
        {
            MoveCategory.Movement => "N",
            MoveCategory.Throw => "U",
            _ => "S"
        };
    }

    private string GetHitAttribute(Hitbox hitbox)
    {
        return hitbox.Type switch
        {
            HitboxType.Attack => "S",
            HitboxType.Projectile => "S",
            HitboxType.Throw => "S",
            _ => "S"
        };
    }

    private string GetHitVelocity(Hitbox hitbox)
    {
        return hitbox.HitLevel switch
        {
            HitLevel.Light => "2, -4",
            HitLevel.Medium => "3, -6",
            HitLevel.Heavy => "4, -8",
            _ => "2, -4"
        };
    }

    private string GetGuardVelocity(Hitbox hitbox)
    {
        return hitbox.HitLevel switch
        {
            HitLevel.Light => "-2",
            HitLevel.Medium => "-3",
            HitLevel.Heavy => "-4",
            _ => "-2"
        };
    }

    private string GetAirVelocity(Hitbox hitbox)
    {
        return hitbox.HitLevel switch
        {
            HitLevel.Light => "2, -4",
            HitLevel.Medium => "3, -6",
            HitLevel.Heavy => "4, -8",
            _ => "2, -4"
        };
    }

    private string NormalizeCommand(string command)
    {
        // Convert common notations to MUGEN format
        return command
            .Replace("QCF", "D, DF, F")
            .Replace("QCB", "D, DB, B")
            .Replace("DP", "F, D, DF")
            .Replace("RDP", "B, D, DB")
            .Replace("HCF", "B, DB, D, DF, F")
            .Replace("HCB", "F, DF, D, DB, B");
    }

    private int GetCommandTime(string command)
    {
        // Estimate command execution time based on complexity
        var complexity = command.Count(c => c == ',' || c == '+' || c == '[' || c == ']');
        return Math.Max(15, complexity * 2);
    }
    public async Task<Result<bool>> ExportCharacterAsync(Guid characterId, string outputDirectory, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Exporting character {CharacterId} to {OutputDir}", characterId, outputDirectory);
        return Result.Success(true);
    }

    public async Task<Result<bool>> ExportCommandsAsync(Guid characterId, string outputPath, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Exporting commands for character {CharacterId} to {OutputPath}", characterId, outputPath);
        return Result.Success(true);
    }

    public async Task<Result<bool>> ExportSpritesAsync(Guid characterId, string outputPath, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Exporting sprites for character {CharacterId} to {OutputPath}", characterId, outputPath);
        return Result.Success(true);
    }

    public async Task<Result<bool>> ExportSoundsAsync(Guid characterId, string outputPath, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Exporting sounds for character {CharacterId} to {OutputPath}", characterId, outputPath);
        return Result.Success(true);
    }

    public async Task<Result<SaveState.Core.Mugen.ValueObjects.ValidationResult>> ValidateExportReadinessAsync(Guid characterId, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Validating export readiness for character {CharacterId}", characterId);
        return Result.Success(new SaveState.Core.Mugen.ValueObjects.ValidationResult
        {
            IsValid = true,
            Summary = "Ready",
            MoveAnalyses = Array.Empty<string>(),
            Recommendations = Array.Empty<string>(),
            ActionableTips = Array.Empty<string>(),
            CharacterName = "",
            BalanceScore = 0,
            PredictedWinRate = 0
        });
    }
}
