#!/usr/bin/env pwsh
# Add all projects to solution in batches

$solutionFile = "SaveStateReborn.sln"
$batchSize = 10

# Get all projects
$srcProjects = Get-ChildItem -Path "src" -Filter "*.csproj" -Recurse | 
    Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" } |
    Select-Object -ExpandProperty FullName

$testProjects = Get-ChildItem -Path "tests" -Filter "*.csproj" -Recurse | 
    Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" } |
    Select-Object -ExpandProperty FullName

$toolProjects = Get-ChildItem -Path "tools" -Filter "*.csproj" -Recurse | 
    Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" -and $_.FullName -notlike "*\BenchmarkDotNet.Autogenerated*" } |
    Select-Object -ExpandProperty FullName

$allProjects = $srcProjects + $testProjects + $toolProjects | Sort-Object

Write-Host "Found $($allProjects.Count) total projects" -ForegroundColor Green
Write-Host "Current solution has ~21 projects" -ForegroundColor Yellow
Write-Host "Need to add: $($allProjects.Count - 21) projects`n" -ForegroundColor Cyan

# Add projects in batches
$total = $allProjects.Count
$current = 0
$success = 0
$failed = 0

foreach ($project in $allProjects) {
    $current++
    $projectName = [System.IO.Path]::GetFileNameWithoutExtension($project)
    
    Write-Host "[$current/$total] Adding $projectName..." -NoNewline
    
    try {
        $result = dotnet sln $solutionFile add $project 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host " OK" -ForegroundColor Green
            $success++
        } else {
            Write-Host " SKIP (already exists or error)" -ForegroundColor Yellow
            $failed++
        }
    } catch {
        Write-Host " ERROR" -ForegroundColor Red
        $failed++
    }
    
    # Small delay every 10 projects to avoid overwhelming the system
    if ($current % $batchSize -eq 0) {
        Start-Sleep -Milliseconds 100
    }
}

Write-Host "`n=================================" -ForegroundColor Cyan
Write-Host "Batch add complete!" -ForegroundColor Green
Write-Host "Successfully added: $success" -ForegroundColor Green
Write-Host "Failed/Skipped: $failed" -ForegroundColor $(if ($failed -gt 0) { "Yellow" } else { "Green" })
Write-Host "Total in solution: $(dotnet sln $solutionFile list | Select-String "\.csproj" | Measure-Object | Select-Object -ExpandProperty Count)" -ForegroundColor Cyan
