#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Adds all relevant projects to the SaveStateReborn solution.
.DESCRIPTION
    This script adds all src, tests, and tools projects to the solution.
    Run this after creating a new solution or to update an existing one.
#>

$ErrorActionPreference = "Stop"

$solutionFile = "SaveStateReborn.sln"
$srcProjects = Get-ChildItem -Path "src" -Recurse -Filter "*.csproj" | 
    Where-Object { 
        $_.FullName -notlike "*\bin\*" -and 
        $_.FullName -notlike "*\obj\*" 
    } |
    Select-Object -ExpandProperty FullName |
    Sort-Object

$testProjects = Get-ChildItem -Path "tests" -Recurse -Filter "*.csproj" | 
    Where-Object { 
        $_.FullName -notlike "*\bin\*" -and 
        $_.FullName -notlike "*\obj\*" 
    } |
    Select-Object -ExpandProperty FullName |
    Sort-Object

$toolProjects = Get-ChildItem -Path "tools" -Recurse -Filter "*.csproj" | 
    Where-Object { 
        $_.FullName -notlike "*\bin\*" -and 
        $_.FullName -notlike "*\obj\*" -and
        $_.FullName -notlike "*\BenchmarkDotNet.Autogenerated*"
    } |
    Select-Object -ExpandProperty FullName |
    Sort-Object

Write-Host "Found $($srcProjects.Count) source projects" -ForegroundColor Green
Write-Host "Found $($testProjects.Count) test projects" -ForegroundColor Green
Write-Host "Found $($toolProjects.Count) tool projects" -ForegroundColor Green

# Create solution folders
$folders = @(
    "01_Core",
    "02_Infrastructure", 
    "03_Application",
    "04_Presentation",
    "05_SDK",
    "06_CLI",
    "07_Plugins",
    "08_Tests",
    "09_Tools"
)

foreach ($folder in $folders) {
    Write-Host "Creating solution folder: $folder" -ForegroundColor Yellow
    dotnet sln $solutionFile add --solution-folder $folder 2>$null
}

# Add projects with their folder structure
Write-Host "`nAdding projects to solution..." -ForegroundColor Cyan

foreach ($project in $srcProjects) {
    $projectName = [System.IO.Path]::GetFileNameWithoutExtension($project)
    
    # Determine folder
    if ($project -like "*\SaveState.Core\*") {
        dotnet sln $solutionFile add $project --solution-folder "01_Core" 2>&1 | Out-Null
    }
    elseif ($project -like "*\SaveState.Infrastructure\*") {
        dotnet sln $solutionFile add $project --solution-folder "02_Infrastructure" 2>&1 | Out-Null
    }
    elseif ($project -like "*\SaveState.Application\*") {
        dotnet sln $solutionFile add $project --solution-folder "03_Application" 2>&1 | Out-Null
    }
    elseif ($project -like "*\SaveState.Presentation\*") {
        dotnet sln $solutionFile add $project --solution-folder "04_Presentation" 2>&1 | Out-Null
    }
    elseif ($project -like "*\SaveState.Sdk\*") {
        dotnet sln $solutionFile add $project --solution-folder "05_SDK" 2>&1 | Out-Null
    }
    elseif ($project -like "*\SaveState.CLI\*") {
        dotnet sln $solutionFile add $project --solution-folder "06_CLI" 2>&1 | Out-Null
    }
    elseif ($project -like "*\Plugins\*") {
        $pluginName = $projectName -replace "SaveState\.Plugins\.", ""
        dotnet sln $solutionFile add $project --solution-folder "07_Plugins" 2>&1 | Out-Null
    }
    else {
        dotnet sln $solutionFile add $project 2>&1 | Out-Null
    }
    
    Write-Host "  Added: $projectName" -ForegroundColor Gray
}

foreach ($project in $testProjects) {
    $projectName = [System.IO.Path]::GetFileNameWithoutExtension($project)
    dotnet sln $solutionFile add $project --solution-folder "08_Tests" 2>&1 | Out-Null
    Write-Host "  Added: $projectName" -ForegroundColor Gray
}

foreach ($project in $toolProjects) {
    $projectName = [System.IO.Path]::GetFileNameWithoutExtension($project)
    dotnet sln $solutionFile add $project --solution-folder "09_Tools" 2>&1 | Out-Null
    Write-Host "  Added: $projectName" -ForegroundColor Gray
}

Write-Host "`nSolution update complete!" -ForegroundColor Green
Write-Host "Run 'dotnet sln list' to verify." -ForegroundColor Cyan
