<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DatabaseTestCollection.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SaveState.Core\SaveState.Core.csproj" />
    <ProjectReference Include="..\..\src\SaveState.Application\SaveState.Application.csproj" />
    <ProjectReference Include="..\..\src\SaveState.Infrastructure\SaveState.Infrastructure.csproj" />
    <ProjectReference Include="..\SaveState.Tests.Fakes\SaveState.Tests.Fakes.csproj" />
    <ProjectReference Include="..\SaveState.Tests.Infrastructure\SaveState.Tests.Infrastructure.csproj" />
  </ItemGroup>

</Project>

